<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Remove="dist\**" />
    <Compile Remove="EdgeLinkExample.cs" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>EdgeLinkSdk</AssemblyName>
    <RootNamespace>EdgeLink</RootNamespace>
    <LangVersion>8</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>
</Project>
